### ISSUE TITLE
Model file doesn't exist: models/catboost_1.model

### ISSUE THREAD

**Issue by AsmaML** [zeeshansayyed/ArabicSOS#2]
hello , thank you so much for sharing your tools 

i'm trying to make it work  , so i followed the instructions by  installing the requierements 
then i have typed the cmd :  wget -v -O catboost_1.model  https://iu.box.com/shared/static/mcu4frnipinfw7ery0wetrax7u7zzsxp.model 

i couldn't install it with the -L parameters i have an error message 

it show that i receive messeges it take a while then it done 
then  i tried this cmd : 
 python segmenter.py sample/wiki_books_test_0.txt -o sample/my_segmented_wiki_books_test_0.txt

i hade this message error : 

Traceback (most recent call last):
  File "segmenter.py", line 46, in <module>
    segment(args.in_file, args.out_file)
  File "segmenter.py", line 24, in segment
    model.load_model("models/catboost_1.model")
  File "c:\users\twins\anaconda3\lib\site-packages\catboost\core.py", line 2589, in load_model
    self._load_model(fname, format)
  File "c:\users\twins\anaconda3\lib\site-packages\catboost\core.py", line 1315, in _load_model
    self._object._load_model(model_file, format)
  File "_catboost.pyx", line 4681, in _catboost._CatBoost._load_model
  File "_catboost.pyx", line 4684, in _catboost._CatBoost._load_model
_catboost.CatBoostError: c:/program files (x86)/go agent/pipelines/buildmaster/catboost.git/catboost/libs/model/model_import_interface.h:19: Model file doesn't exist: models/catboost_1.model

could you help me please ?! i need this tool so much 
thank you

**Comment by zeeshansayyed** [comment]
@AsmaZbt 

Can you please share the error message that you get when you type: 
`wget -v -O catboost_1.model https://iu.box.com/shared/static/mcu4frnipinfw7ery0wetrax7u7zzsxp.model`

Which operating system are you using?

If wget is not working, can you manually download the model file from the Box link?

**Comment by AsmaML** [comment]
thank you so much for answering 

I'm working on windows 10

i did not get  any error message when i type :
wget -v -O catboost_1.model https://iu.box.com/shared/static/mcu4frnipinfw7ery0wetrax7u7zzsxp.model


finally it's working by manually download the model file .
but i needed to create file models then put the downloaded model inside. 
then adding the syntaxe : encoding ='utf8' in each open() file function in the script 
then  it work greats ! 
thank you so much for helping and sharing this beautifull work (y)

**Comment by AsmaML** [comment]
excuse me again but how can I cite this work please?

**Comment by zeeshansayyed** [comment]
You are welcome @AsmaZbt 

This is the paper: **https://dl.acm.org/doi/pdf/10.1145/3322905.3322927**

You can use the following citation.

```bibtex
@inproceedings{10.1145/3322905.3322927,
author = {Mohamed, Emad and Sayyed, Zeeshan Ali},
title = {Arabic-SOS: Segmentation, Stemming, and Orthography Standardization for Classical and Pre-Modern Standard Arabic},
year = {2019},
isbn = {9781450371940},
publisher = {Association for Computing Machinery},
address = {New York, NY, USA},
url = {https://doi.org/10.1145/3322905.3322927},
doi = {10.1145/3322905.3322927},
booktitle = {Proceedings of the 3rd International Conference on Digital Access to Textual Cultural Heritage},
pages = {27–32},
numpages = {6},
keywords = {morphological segmentation, orthography standardization, classical arabic},
location = {Brussels, Belgium},
series = {DATeCH2019}
}
```
